-- TPerl UnitFrames
-- Author: TULOA
-- License: GNU GPL v3, 29 June 2007 (see LICENSE.txt)

-- Localizations

if (GetLocale() == "zhTW") then

TPERL_RAID_GROUP		= "隊伍 %d"
TPERL_RAID_TOOLTIP_OFFLINE	= "%s 已離線"
TPERL_RAID_TOOLTIP_AFK		= "%s 已暫離"
TPERL_RAID_TOOLTIP_DND		= "%s 已勿擾"
TPERL_RAID_TOOLTIP_DYING	= "%s 已死亡"
TPERL_RAID_TOOLTIP_REBIRTH	= "%s 已戰復"
TPERL_RAID_TOOLTIP_ANKH		= "%s 已死者復生"
TPERL_RAID_TOOLTIP_SOULSTONE	= "%s 已綁定靈魂石"

TPERL_RAID_TOOLTIP_REMAINING	= " 剩餘"

TPERL_RAID_DROPDOWN_SHOWPET	= "顯示寵物"
TPERL_RAID_DROPDOWN_SHOWOWNER	= "顯示擁有者"

TPERL_RAID_DROPDOWN_MAINTANKS	= "主坦"
TPERL_RAID_DROPDOWN_SETMT	= "設為主坦 #%d"
TPERL_RAID_DROPDOWN_REMOVEMT	= "移除主坦 #%d"

TPERL_RAID_RESSING		= " 復活中"
TPERL_RAID_AFK			= "暫離"
TPERL_RAID_DND			= "勿擾"
TPERL_RAID_AUTOPROMOTE		= "自動晉級"
TPERL_RAID_RESSER_AVAIL		= "可施展復活技能者仍有："

end
