
TPERL_RAID_MONITOR_TITLE				= "Casting Monitor"
TPERL_RAID_MONITOR_TOTALS				= "Toggle display of Totals and Statistics"

TPERL_RAID_MONITOR_STATS_RAID_MANA		= "Raid Mana"
TPERL_RAID_MONITOR_STATS_HIGH_MANA		= "High Mana"
TPERL_RAID_MONITOR_STATS_LOW_MANA		= "Low Mana"
TPERL_RAID_MONITOR_STATS_RAID_HEALTH	= "Raid Health"

TPERL_MONITOR_LEFTCLICK					= "|c00FFFFFFLeft Click|r to %s"
TPERL_MONITOR_RIGHTCLICK				= "|c00FFFFFFRight Click|r to %s"
TPERL_MONITOR_CLICKCAST					= "cast |c0000FF00%s|r"
TPERL_MONITOR_CLICKTARGET				= "|c00FFFF80target|r"

TPERL_MONITOR_INNERVATE					= "Innervate"
TPERL_MONITOR_MANATIDE					= "Mana Tide Totem"

TPERL_LOC_OOR							= "n/a"
