if (GetLocale() == "zhCN") then
	TPERL_RAID_MONITOR_TITLE		= "施法监视"
	TPERL_RAID_MONITOR_TOTALS		= "切换显示所有状态监视"

	TPERL_RAID_MONITOR_STATS_RAID_MANA	= "团队法力"
	TPERL_RAID_MONITOR_STATS_HIGH_MANA	= "高法力"
	TPERL_RAID_MONITOR_STATS_LOW_MANA	= "低法力"
	TPERL_RAID_MONITOR_STATS_RAID_HEALTH	= "团队治疗"

	TPERL_MONITOR_LEFTCLICK			= "|c00FFFFFF左键点击|r 以 %s"
	TPERL_MONITOR_RIGHTCLICK		= "|c00FFFFFF右键点击|r 以 %s"
	TPERL_MONITOR_CLICKCAST			= "施放 |c0000FF00%s|r"
	TPERL_MONITOR_CLICKTARGET		= "|c00FFFF80目标|r"

	TPERL_MONITOR_INNERVATE		= "激活"
	TPERL_MONITOR_MANATIDE		= "法力之潮图腾"

	TPERL_LOC_OOR				= "n/a"
end
