if (GetLocale() == "zhTW") then
	TPERL_RAID_MONITOR_TITLE		= "施法監視 |c00A04040(BETA)|r"
	TPERL_RAID_MONITOR_TOTALS		= "切換顯示所有狀態監視"

	TPERL_RAID_MONITOR_STATS_RAID_MANA	= "團隊法力"
	TPERL_RAID_MONITOR_STATS_HIGH_MANA	= "高法力"
	TPERL_RAID_MONITOR_STATS_LOW_MANA	= "低法力"
	TPERL_RAID_MONITOR_STATS_RAID_HEALTH	= "團隊治療"

	TPERL_MONITOR_LEFTCLICK			= "|c00FFFFFF左鍵點擊|r 來 %s"
	TPERL_MONITOR_RIGHTCLICK		= "|c00FFFFFF右鍵點擊|r 來 %s"
	TPERL_MONITOR_CLICKCAST			= "施放 |c0000FF00%s|r"
	TPERL_MONITOR_CLICKTARGET		= "|c00FFFF80目標|r"

	TPERL_MONITOR_INNERVATE			= "啟動"
	TPERL_MONITOR_MANATIDE			= "法力之潮圖騰"

	TPERL_LOC_OOR				= "超出距離"
end
